ent = input('Digite algo para ser analizado: ')
print('A entrada é do tipo: {}'.format(type(ent)))
print('A entrada é alfanumerica? {}'.format(ent.isalnum()))
print('A entrada é alfabética? {}'.format(ent.isalpha()))
print('A entrada é um digito? {}'.format(ent.isdigit()))
print('A entrada é somente minuscula? {}'.format(ent.islower()))
print('A entrada é um decimal? {}'.format(ent.isdecimal()))
print('A entrada é um numero? {}'.format(ent.isnumeric()))
print('A entrada é um espaço? {}'.format(ent.isspace()))
print('A entrada é algo que pode ser impresso? {}'.format(ent.isprintable()))
print('A entrada é tuda maiusculo? {}'.format(ent.isupper()))